Added different plan options
arjunatapadkar/codeteria pull request #194
Opened 2024-10-19 16:34 UTC by shivenyadavs

Payment Plans Section: Below the "Coming Soon" part, I added a section that includes three payment options: Monthly Pro, Yearly Pro, and College Plan.
Buttons: Each plan has a corresponding button (Subscribe now or Buy now), which navigates to specific routes (/payment/monthly-pro, /payment/yearly-pro, /payment/college-plan). You'll need to handle these routes in your app's routing logic.
Styling: I used similar Tailwind classes to maintain the design consistency.

2024-10-19 16:37 UTC, shivenyadavs commented
@arjunatapadkar can you please check the changes which i made.

2024-10-19 16:52 UTC, shivenyadavs commented
![Screenshot (71)](https://github.com/user-attachments/assets/be5d3724-225c-402a-abb6-60f30da33db1)
here is the code snap shot

2024-10-19 16:57 UTC, arjunatapadkar commented
Snapshots of ui will be more helpful

2024-10-19 16:59 UTC, arjunatapadkar requested changes
Don't change upcoming page 

Create a new Page for Pro

2024-10-19 17:32 UTC, shivenyadavs commented
i made the changes can you please check it

2024-10-20 02:03 UTC, arjunatapadkar commented
And share snapshot of ui for pro page

2024-10-20 02:08 UTC, arjunatapadkar commented on src/pages/Homepage.jsx
page: "/pro"

2024-10-20 07:03 UTC, shivenyadavs commented
@arjunatapadkar  added page pro and made changes in the Homepage.jsx

2024-10-20 12:58 UTC, arjunatapadkar approved these changes

2024-10-20 12:59 UTC, merged